### ISSUE TITLE
Quicksilver decreases a flask only to the player who delivers it

### ISSUE THREAD

**Issue by estebanruizrodriguez** [BrandenEK/Blasphemous-Multiplayer#5]
When a player deliver a quicksilver, the number of flasks decreases by one, but the other players still have the same number of flasks.

Steps to reproduce:
- Player1 and Player2 have 4 flasks
- Player1 delivers a quicksilver
- Player1 has 3 upgraded flasks. Player2 has 4 upgraded flasks

Strange behavior also occurs when a player fills a new flask. Sometimes it increases the number of flasks of all the team, other times it restores the missing flask without affecting the others...

PS: Thanks for the amazing work you are doing with all these mods! 💘

**Comment by BrandenEK** [comment]
Interesting, I was not aware of this behavior.  Thank you for bringing it to my attention; I will look more into this soon.

**Comment by BrandenEK** [comment]
This issue has (finally) been fixed and will be available in the next release
